//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Web.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.Web.Web.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string buttonRemove {
            get {
                return ResourceManager.GetString("buttonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string buttonSubmit {
            get {
                return ResourceManager.GetString("buttonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string labelActivities {
            get {
                return ResourceManager.GetString("labelActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string labelAvailable {
            get {
                return ResourceManager.GetString("labelAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        internal static string labelCapacity {
            get {
                return ResourceManager.GetString("labelCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string labelDescription {
            get {
                return ResourceManager.GetString("labelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusions.
        /// </summary>
        internal static string labelExclusions {
            get {
                return ResourceManager.GetString("labelExclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string labelFirstName {
            get {
                return ResourceManager.GetString("labelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclusions.
        /// </summary>
        internal static string labelInclusions {
            get {
                return ResourceManager.GetString("labelInclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string labelLastName {
            get {
                return ResourceManager.GetString("labelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string labelName {
            get {
                return ResourceManager.GetString("labelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of customer.
        /// </summary>
        internal static string labelNumberOfCustomer {
            get {
                return ResourceManager.GetString("labelNumberOfCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of day.
        /// </summary>
        internal static string labelNumberOfDays {
            get {
                return ResourceManager.GetString("labelNumberOfDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Room.
        /// </summary>
        internal static string labelNumberOfRoom {
            get {
                return ResourceManager.GetString("labelNumberOfRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Class.
        /// </summary>
        internal static string labelRoomClass {
            get {
                return ResourceManager.GetString("labelRoomClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string labelRoomName {
            get {
                return ResourceManager.GetString("labelRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomType.
        /// </summary>
        internal static string labelRoomType {
            get {
                return ResourceManager.GetString("labelRoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string labelSelect {
            get {
                return ResourceManager.GetString("labelSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What To Take.
        /// </summary>
        internal static string labelWhatToTake {
            get {
                return ResourceManager.GetString("labelWhatToTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add baby.
        /// </summary>
        internal static string stringAddBaby {
            get {
                return ResourceManager.GetString("stringAddBaby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add child.
        /// </summary>
        internal static string stringAddChild {
            get {
                return ResourceManager.GetString("stringAddChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        internal static string stringBook {
            get {
                return ResourceManager.GetString("stringBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer infomation.
        /// </summary>
        internal static string stringCustomerInfo {
            get {
                return ResourceManager.GetString("stringCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail&gt;&gt;.
        /// </summary>
        internal static string stringDetail {
            get {
                return ResourceManager.GetString("stringDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room #.
        /// </summary>
        internal static string stringRoomNo {
            get {
                return ResourceManager.GetString("stringRoomNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        internal static string stringRoomNotAvailable {
            get {
                return ResourceManager.GetString("stringRoomNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        internal static string stringTotalPrice {
            get {
                return ResourceManager.GetString("stringTotalPrice", resourceCulture);
            }
        }
    }
}
