using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliant(false)]
[assembly: ComVisible(false)]
[assembly: AssemblyTitle("Core for KIT CMS")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("K.I.T JSC")]
[assembly: AssemblyProduct("KIT CMS")]
[assembly: AssemblyCopyright("2008 K.I.T. All rights reserved.")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.5.2.676")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AllowPartiallyTrustedCallers]