using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("KIT CMS ServerControls")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyCompanyAttribute("K.I.T JSC")]
[assembly: AssemblyProductAttribute("KIT CMS")]
[assembly: AssemblyCopyrightAttribute("2008 K.I.T JSC. All rights reserved.")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.5.1.676")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: AllowPartiallyTrustedCallersAttribute()]

